=== CIFPDAW/Lenguaje-de-Marcas/XML/XML10/persona.dtd
<!ELEMENT Personas (persona*)>
<!ELEMENT persona (Nombre, Nacimiento, Direccion, Varon)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Nacimiento (#PCDATA)>
<!ATTLIST Nacimiento dia NMTOKEN #REQUIRED>
<!ATTLIST Nacimiento mes NMTOKEN #REQUIRED>
<!ATTLIST Nacimiento anyo NMTOKEN #REQUIRED>
<!ELEMENT Direccion (Calle, poblacion, Provincia, cpostal)>
<!ELEMENT Calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT Provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT Varon (#PCDATA)>

=== CIFPDAW/Lenguaje-de-Marcas/XML10/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Personas SYSTEM "persona.dtd">

<Personas>
    <persona>
        <Nombre>
            Juan Pardo
        </Nombre>
        <Nacimiento dia="10" mes="Abril" anyo="1982" />
        <Direccion>
            <Calle>
                Caoba, 1
            </Calle>
            <poblacion>
                Madrid
            </poblacion>
            <Provincia>
                Madrid
            </Provincia>
            <cpostal>
                28005
            </cpostal>
        </Direccion>
        <Varon />
    </persona>
</Personas>
